---
- name: Installing Nagios4 Dependencies and Libraries
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php
      - libgd-dev
      - openssl
      - libssl-dev
      - autoconf
      - gcc
      - libc6
      - libmcrypt-dev
      - make
      - libssl-dev
      - wget
      - bc
      - gawk
      - dc
      - build-essential
      - snmp
      - libnet-snmp-perl
      - gettext
      - python3-pip
    state: latest

- name: Install passlib Python Package
  apt:
    name: python3-passlib
    state: present

- name: Install passlib Python Package
  apt:
    name: python3-passlib
    state: present

- name: Creating a directory for the downloaded files
  file:
    path: ~/nagios
    state: directory

- name: Setting User and Password
  community.general.htpasswd:
    path: /usr/local/nagios4/etc/htpasswd.users
    name: jcastillo
    password: 1234567
    
- name: Confirmation of Nagios is enabled
  service:
    name: nagios4
    state: restarted
    enabled: true


- name: Confirmation of httpd is enabled
  service:
    name: apache2
    state: started
    enabled: true

- name: Downloading and Extracting Nagios from Github
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Creating Users and Group, compiling and installation of Nagios
  shell:
    cd ~/nagios/nagioscore-*
    sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
    sudo make all
    sudo make install-groups-users
    sudo usermod -a -G nagios www-data
    sudo make install
    sudo make install-daemoninit
    sudo make install-commandmode
    sudo make install-config
    sudo make install-webconf
    sudo a2enmod rewrite
    sudo a2enmod cgi

- name: Downloading and Extracting plugins of Nagios from Github
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Compiling and Installing Nagios plugins
  shell:
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install
